### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by CaptBoscho** [sitespeedio/chrome-har#110]
On version 0.13.2, getting this error fairly consistently:

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at M.m.toISOString (/app/node_modules/chrome-har/node_modules/dayjs/dayjs.min.js:1:6270)
    at module.exports (/app/node_modules/chrome-har/lib/entryFromResponse.js:185:53)
    at harFromMessages (/app/node_modules/chrome-har/index.js:410:15)

**Comment by soulgalore** [comment]
Hi @CaptBoscho thanks for creating the issue, I haven't seen that one. What Chrome version are you using and can you please share the trace from Chrome so I can reproduce it?

**Comment by CaptBoscho** [comment]
We are on version 115.0.5790.98-1. I will try to get those chrome traces

**Comment by soulgalore** [comment]
So in your case you also get the date in capital letters is that correct?
